A=input("saisir le nom de la premiere article: ")
n=int(input("saisir la quantite de la premiere article :"))
p=int(input("saisir le prix unitaire de la premiere quantite:"))
c=input("saisir le nom de la deuxieme article: ")
m=int(input("saisir la quantite de la  deuxieme article :"))
l=int(input("saisir le prix unitaire de la  deuxieme quantite:"))
print("le total pour la deuxieme article est :",n *  p)
print("le total pour la deuxieme article est :",l *  m)
print("le total de la facture HT :",(n * p) + (l *  m))
print("le total de la facture TTC ",((n * p) + (l *  m)) +((n * p) + (l *  m))*0.2)
